{% set name = "PyIRI" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiri-{{ version }}.tar.gz
  sha256: 303b8d228a994f9f907bfa659b84cadb94ad84dfccbc96e53074b70e1427e636

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=38.6
    - pip >=10
  run:
    - python >={{ python_min }}
    - fortranformat
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - PyIRI
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/victoriyaforsythe/PyIRI
  summary: Python implementation of International Reference Ionosphere
  dev_url: https://github.com/victoriyaforsythe/PyIRI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - opoplawski
